### ISSUE TITLE
Unable to authenticate against Bot Framework

### ISSUE THREAD

**Issue by irbbez** [Microsoft/botbuilder-python#102]
We tried to prototype a Skype Bot with a custom ubuntu server. As a basis we use the sample echo bot from this repository. We host the Server on Port 443 and wrap the Socket with the Python ssl module.

```
try:
    SERVER = http.server.HTTPServer(('', 443), BotRequestHandler)
    SERVER.socket = ssl.wrap_socket (SERVER.socket, 
        keyfile="server.key", 
        certfile='server.cert', server_side=True)
    print('Started http server')
    SERVER.serve_forever()
except KeyboardInterrupt:
    print('^C received, shutting down server')
SERVER.socket.close()
```

With our Setup we are able to connect our Bot to the Bot Framework and receive Messages. However, the Server does not answer (send response 401). We tried to Debug this Error and found that the error is within the authentication. We modified the Code to track the error and added some print Statements in the functions and print out the error in the authentication.

```
def do_POST(self):
        body = self.rfile.read(int(self.headers['Content-Length']))
        data = json.loads(str(body, 'utf-8'))
        activity = Activity.deserialize(data)
        
        print("do_post", activity.text)

        if not self.__handle_authentication(activity):
            print("handle_auth")
            return

        if activity.type == ActivityTypes.conversation_update.value:
            print("conv_upd")
            self.__handle_conversation_update_activity(activity)
        elif activity.type == ActivityTypes.message.value:
            print("msg_value")
            self.__handle_message_activity(activity)
        else:
            print("else")
            self.__unhandled_activity()
```

and

```
def __handle_authentication(self, activity):
        credential_provider = SimpleCredentialProvider(APP_ID, APP_PASSWORD)
        loop = asyncio.new_event_loop()
        try:
            loop.run_until_complete(JwtTokenValidation.authenticate_request(
                activity, self.headers.get("Authorization"), credential_provider))
            print("Try")
            return True
        except Exception as ex:
            print(ex)
            self.send_response(401, ex)
            self.end_headers()
            print("except")
            return False
        finally:
            print("fin")
            loop.close()
```

When we now send a message ("Hello Bot") to the Bot we get the following Output:

```
do_post Hello Bot

Task <Task pending coro=<JwtTokenValidation.authenticate_request() running at /home/ubuntu/.local/lib/python3.5/site-packages/botframework/connector/auth/jwt_token_validation.py:34> cb=[_run_until_complete_cb() at /usr/lib/python3.5/asyncio/base_events.py:164]> got Future <Task pending coro=<ChannelValidation.authenticate_token() running at /home/ubuntu/.local/lib/python3.5/site-packages/botframework/connector/auth/channel_validation.py:51>> attached to a different loop

52.164.229.112 - - [02/Aug/2018 07:44:41] "POST / HTTP/1.1" 401 -

except

fin

handle_auth
```

Is this an error from our Setup or in the sdk? How can we fix this error? Any help is appreciated.
AppId and password are handed over correct to the auth function and we also generated new passwords and tried with them -> No Change.
We use the latest stable releases installed via pip3.

**Comment by jwiley84** [comment]
Attemping to reproduce error.

**Comment by kcm117** [comment]
I've run into the same issue after deploying to an Azure App Service with the following versions:

botbuilder-core                                4.0.0a6
botbuilder-schema                           4.0.0a6
botframework-connector                  4.0.0a6

I've confirmed that the AppId and App Password are correct.  They are stored in App Service "Application Settings" environment variables named MicrosoftAppId and MicrosoftAppPassword. They are referenced in the bot code as follows:

`APP_ID = str(os.environ.get('MicrosoftAppId'))
APP_PASSWORD = str(os.environ.get('MicrosoftAppPassword'))`

The authentication function is as follows:

`    def __handle_authentication(self, activity):
        credential_provider = SimpleCredentialProvider(APP_ID, APP_PASSWORD)
        loop = asyncio.new_event_loop()
        try:
            loop.run_until_complete(JwtTokenValidation.authenticate_request(
                activity, self.headers.get("Authorization"), credential_provider))
            return True
        except Exception as ex:
            print(ex)
            self.send_response(401, ex)
            self.end_headers()
            return False
        finally:
            loop.close()
`
After debuginning locally, 401 error is returned when attempting to authenticate:

`----------------------------------------
127.0.0.1 - - [09/Aug/2018 12:56:24] "POST /api/messages HTTP/1.1" 202 -
127.0.0.1 - - [09/Aug/2018 12:56:27] "POST /api/messages HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 61481)
Traceback (most recent call last):
  File "C:\toolkits\anaconda-3.5.1.0\envs\pybots\lib\site-packages\msrest\service_client.py", line 235, in send
    session = self.creds.signed_session(self._session)
TypeError: signed_session() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\toolkits\anaconda-3.5.1.0\envs\pybots\lib\socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\toolkits\anaconda-3.5.1.0\envs\pybots\lib\socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "C:\toolkits\anaconda-3.5.1.0\envs\pybots\lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\toolkits\anaconda-3.5.1.0\envs\pybots\lib\socketserver.py", line 696, in __init__
    self.handle()
  File "C:\toolkits\anaconda-3.5.1.0\envs\pybots\lib\http\server.py", line 418, in handle
    self.handle_one_request()
  File "C:\toolkits\anaconda-3.5.1.0\envs\pybots\lib\http\server.py", line 406, in handle_one_request
    method()
  File "c:\Users\kcmunnin\OneDrive - Microsoft\repo\pybot\main.py", line 78, in do_POST
    self.__handle_message_activity(activity)
  File "c:\Users\kcmunnin\OneDrive - Microsoft\repo\pybot\main.py", line 46, in __handle_message_activity
    connector.conversations.send_to_conversation(reply.conversation.id, reply)
  File "C:\toolkits\anaconda-3.5.1.0\envs\pybots\lib\site-packages\botframework\connector\operations\conversations_operations.py", line 229, in send_to_conversation
    request, header_parameters, body_content, stream=False, **operation_config)
  File "C:\toolkits\anaconda-3.5.1.0\envs\pybots\lib\site-packages\msrest\service_client.py", line 237, in send
    session = self.creds.signed_session()
  File "C:\toolkits\anaconda-3.5.1.0\envs\pybots\lib\site-packages\botframework\connector\auth\microsoft_app_credentials.py", line 59, in signed_session
    basic_authentication = BasicTokenAuthentication({"access_token": self.get_access_token()})
  File "C:\toolkits\anaconda-3.5.1.0\envs\pybots\lib\site-packages\botframework\connector\auth\microsoft_app_credentials.py", line 81, in get_access_token
    oauth_token = self.refresh_token()
  File "C:\toolkits\anaconda-3.5.1.0\envs\pybots\lib\site-packages\botframework\connector\auth\microsoft_app_credentials.py", line 94, in refresh_token
    response.raise_for_status()
  File "C:\toolkits\anaconda-3.5.1.0\envs\pybots\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token
----------------------------------------`

**Comment by kcm117** [comment]
I've run into the same issue after deploying to an Azure App Service with the following versions:
```
botbuilder-core    4.0.0a6
botbuilder-schema     4.0.0a6
botframework-connector    4.0.0a6
```
I've confirmed that the AppId and App Password are correct.  They are stored in App Service "Application Settings" environment variables named MicrosoftAppId and MicrosoftAppPassword. 

![image](https://user-images.githubusercontent.com/11845433/43918092-1edbc746-9be0-11e8-8f9c-64fa8072924e.png)

They are referenced in the bot code as follows:

```
APP_ID = str(os.environ.get('MicrosoftAppId'))
APP_PASSWORD = str(os.environ.get('MicrosoftAppPassword'))
```
The authentication function is as follows:

```
    def __handle_authentication(self, activity):
        credential_provider = SimpleCredentialProvider(APP_ID, APP_PASSWORD)
        loop = asyncio.new_event_loop()
        try:
            loop.run_until_complete(JwtTokenValidation.authenticate_request(
                activity, self.headers.get("Authorization"), credential_provider))
            return True
        except Exception as ex:
            print(ex)
            self.send_response(401, ex)
            self.end_headers()
            return False
        finally:
            loop.close()
```

After debuginning locally, 401 error is returned when attempting to authenticate:

```
----------------------------------------
127.0.0.1 - - [09/Aug/2018 12:56:24] "POST /api/messages HTTP/1.1" 202 -
127.0.0.1 - - [09/Aug/2018 12:56:27] "POST /api/messages HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 61481)
Traceback (most recent call last):
  File "C:\toolkits\anaconda-3.5.1.0\envs\pybots\lib\site-packages\msrest\service_client.py", line 235, in send
    session = self.creds.signed_session(self._session)
TypeError: signed_session() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\toolkits\anaconda-3.5.1.0\envs\pybots\lib\socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\toolkits\anaconda-3.5.1.0\envs\pybots\lib\socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "C:\toolkits\anaconda-3.5.1.0\envs\pybots\lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\toolkits\anaconda-3.5.1.0\envs\pybots\lib\socketserver.py", line 696, in __init__
    self.handle()
  File "C:\toolkits\anaconda-3.5.1.0\envs\pybots\lib\http\server.py", line 418, in handle
    self.handle_one_request()
  File "C:\toolkits\anaconda-3.5.1.0\envs\pybots\lib\http\server.py", line 406, in handle_one_request
    method()
  File "c:\Users\kcmunnin\OneDrive - Microsoft\repo\pybot\main.py", line 78, in do_POST
    self.__handle_message_activity(activity)
  File "c:\Users\kcmunnin\OneDrive - Microsoft\repo\pybot\main.py", line 46, in __handle_message_activity
    connector.conversations.send_to_conversation(reply.conversation.id, reply)
  File "C:\toolkits\anaconda-3.5.1.0\envs\pybots\lib\site-packages\botframework\connector\operations\conversations_operations.py", line 229, in send_to_conversation
    request, header_parameters, body_content, stream=False, **operation_config)
  File "C:\toolkits\anaconda-3.5.1.0\envs\pybots\lib\site-packages\msrest\service_client.py", line 237, in send
    session = self.creds.signed_session()
  File "C:\toolkits\anaconda-3.5.1.0\envs\pybots\lib\site-packages\botframework\connector\auth\microsoft_app_credentials.py", line 59, in signed_session
    basic_authentication = BasicTokenAuthentication({"access_token": self.get_access_token()})
  File "C:\toolkits\anaconda-3.5.1.0\envs\pybots\lib\site-packages\botframework\connector\auth\microsoft_app_credentials.py", line 81, in get_access_token
    oauth_token = self.refresh_token()
  File "C:\toolkits\anaconda-3.5.1.0\envs\pybots\lib\site-packages\botframework\connector\auth\microsoft_app_credentials.py", line 94, in refresh_token
    response.raise_for_status()
  File "C:\toolkits\anaconda-3.5.1.0\envs\pybots\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token
----------------------------------------

```

After retrying an hour later, the same code worked without changes locally.  I still receive a 401 error when attempting to access the bot deployed to Azure App Service.

**Comment by CoHealer** [comment]
Closing due to inactivity. If it requires more attention please reopen.
