### ISSUE TITLE
KeyError: 'access_token' when calling TeamsInfo.get_team_details(turn_context)

### ISSUE THREAD

**Issue by sferdi0** [microsoft/botbuilder-python#1574]
- Botframework v4 - latest HEAD
- Ubuntu 20.04

Whenever I call `TeamsInfo.get_team_details(turn_context)` I will get an error.

### Code

```python3
from botbuilder.core.teams import TeamsInfo

class BotHandler(TeamsActivityHandler):
    async def on_teams_members_added(
            self,
            teams_members_added: [TeamsChannelAccount],
            team_info: TeamInfo,
            turn_context: TurnContext
    ):
        team_info = await TeamsInfo.get_team_details(turn_context)
```

### Error

Error from response:

```text
AADSTS700016: Application with identifier 'd3164aa4-04a1-4a3f-8ac7-614b28320b89' was not found in the directory 'd6d49420-f39b-4df7-a1dc-d59a935871db'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
Trace ID: 989e6b47-e2f1-4c8a-8551-0303c0141c00
Correlation ID: 4b2cb5bf-d720-4df3-8b04-bd04811822ce
Timestamp: 2021-03-11 15:36:34Z
```

Traceback:

```text
 [on_turn_error] unhandled error: 'access_token'
Traceback (most recent call last):
  File "/home/user/my_app/venv/lib/python3.8/site-packages/botbuilder/core/bot_adapter.py", line 127, in run_pipeline
    return await self._middleware.receive_activity_with_status(
  File "/home/user/my_app/venv/lib/python3.8/site-packages/botbuilder/core/middleware_set.py", line 69, in receive_activity_with_status
    return await self.receive_activity_internal(context, callback)
  File "/home/user/my_app/venv/lib/python3.8/site-packages/botbuilder/core/middleware_set.py", line 79, in receive_activity_internal
    return await callback(context)
  File "/home/user/my_app/venv/lib/python3.8/site-packages/botbuilder/core/activity_handler.py", line 70, in on_turn
    await self.on_conversation_update_activity(turn_context)
  File "/home/user/my_app/venv/lib/python3.8/site-packages/botbuilder/core/teams/teams_activity_handler.py", line 489, in on_conversation_update_activity
    return await self.on_teams_members_added_dispatch(
  File "/home/user/my_app/venv/lib/python3.8/site-packages/botbuilder/core/teams/teams_activity_handler.py", line 711, in on_teams_members_added_dispatch
    return await self.on_teams_members_added(
  File "/home/user/my_app/my_app-bothandler/bothandler/bot/handler.py", line 49, in on_teams_members_added
    team_info = await TeamsInfo.get_team_details(turn_context)
  File "/home/user/my_app/venv/lib/python3.8/site-packages/botbuilder/core/teams/teams_info.py", line 71, in get_team_details
    return teams_connector.teams.get_team_details(team_id)
  File "/home/user/my_app/venv/lib/python3.8/site-packages/botframework/connector/teams/operations/teams_operations.py", line 131, in get_team_details
    response = self._client.send(request, stream=False, **operation_config)
  File "/home/user/my_app/venv/lib/python3.8/site-packages/msrest/service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File "/home/user/my_app/venv/lib/python3.8/site-packages/msrest/pipeline/__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "/home/user/my_app/venv/lib/python3.8/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/home/user/my_app/venv/lib/python3.8/site-packages/msrest/pipeline/requests.py", line 65, in send
    self._creds.signed_session(session)
  File "/home/user/my_app/venv/lib/python3.8/site-packages/botframework/connector/auth/app_credentials.py", line 98, in signed_session
    auth_token = self.get_access_token()
  File "/home/user/my_app/venv/lib/python3.8/site-packages/botframework/connector/auth/microsoft_app_credentials.py", line 65, in get_access_token
    return auth_token["access_token"]
KeyError: 'access_token'
```

## Example 2

Sending a normal message does not work either;

```python3
    async def on_message_activity(
        self,
        turn_context: TurnContext,
        **kwargs
    ):
        await turn_context.send_activity(
            "To continue to run this bot, please fix the bot source code."
        )
```

### Error 2

```text
 [on_turn_error] unhandled error: 'access_token'
Traceback (most recent call last):
  File "/home/user/my_app/venv/lib/python3.8/site-packages/botbuilder/core/bot_adapter.py", line 127, in run_pipeline
    return await self._middleware.receive_activity_with_status(
  File "/home/user/my_app/venv/lib/python3.8/site-packages/botbuilder/core/middleware_set.py", line 69, in receive_activity_with_status
    return await self.receive_activity_internal(context, callback)
  File "/home/user/my_app/venv/lib/python3.8/site-packages/botbuilder/core/middleware_set.py", line 79, in receive_activity_internal
    return await callback(context)
  File "/home/user/my_app/venv/lib/python3.8/site-packages/botbuilder/core/activity_handler.py", line 68, in on_turn
    await self.on_message_activity(turn_context)
  File "/home/user/my_app/my_app-bothandler/bothandler/bot/handler.py", line 140, in on_message_activity
    e = await turn_context.send_activity(
  File "/home/user/my_app/venv/lib/python3.8/site-packages/botbuilder/core/turn_context.py", line 174, in send_activity
    result = await self.send_activities([activity_or_text])
  File "/home/user/my_app/venv/lib/python3.8/site-packages/botbuilder/core/turn_context.py", line 226, in send_activities
    return await self._emit(self._on_send_activities, output, logic())
  File "/home/user/my_app/venv/lib/python3.8/site-packages/botbuilder/core/turn_context.py", line 304, in _emit
    return await logic
  File "/home/user/my_app/venv/lib/python3.8/site-packages/botbuilder/core/turn_context.py", line 221, in logic
    responses = await self.adapter.send_activities(self, output)
  File "/home/user/my_app/venv/lib/python3.8/site-packages/botbuilder/core/bot_framework_adapter.py", line 729, in send_activities
    raise error
  File "/home/user/my_app/venv/lib/python3.8/site-packages/botbuilder/core/bot_framework_adapter.py", line 714, in send_activities
    response = await client.conversations.reply_to_activity(
  File "/home/user/my_app/venv/lib/python3.8/site-packages/botframework/connector/aio/operations_async/_conversations_operations_async.py", line 528, in reply_to_activity
    response = await self._client.async_send(
  File "/home/user/my_app/venv/lib/python3.8/site-packages/msrest/async_client.py", line 115, in async_send
    pipeline_response = await self.config.pipeline.run(request, **kwargs)
  File "/home/user/my_app/venv/lib/python3.8/site-packages/msrest/pipeline/async_abc.py", line 159, in run
    return await first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "/home/user/my_app/venv/lib/python3.8/site-packages/msrest/pipeline/async_abc.py", line 79, in send
    response = await self.next.send(request, **kwargs)  # type: ignore
  File "/home/user/my_app/venv/lib/python3.8/site-packages/msrest/pipeline/async_requests.py", line 99, in send
    self._creds.signed_session(session)
  File "/home/user/my_app/venv/lib/python3.8/site-packages/botframework/connector/auth/app_credentials.py", line 98, in signed_session
    auth_token = self.get_access_token()
  File "/home/user/my_app/venv/lib/python3.8/site-packages/botframework/connector/auth/microsoft_app_credentials.py", line 65, in get_access_token
    return auth_token["access_token"]
KeyError: 'access_token'
```

### Some context

1. My app is sideloaded with a custom `.zip`
2. My app registration has been done under the correct tenant
3. My app configuration (manifest) should be OK as far as I can tell
4. I also created a "Bot Services Channel" with the same AppId as point 3.
  - The password is set to a client secret generated @ app registration

### Questions

1. Did I create the App Registration in a wrong way?
2. Did I create the Bot Channels Registration in a wrong way?

I think this is a bug because I think I setup everything correctly, and configured my bot/app correctly, so I am posting it here.

**Comment by mattsmall1972** [comment]
I am experiencing a similar issue - what was the resolution for this?
