### ISSUE TITLE
update_activity giving an unknown error 

### ISSUE THREAD

**Issue by sethteo** [microsoft/botbuilder-python#2136]
## Version
4

## Describe the bug
Following the botbuilder-sample ([here](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/update-and-delete-bot-messages?tabs=python)) attempted to test out the code but continued to get (ServiceError) Unknown

Partial error trace:
Error processing request: (ServiceError) Unknown
Traceback (most recent call last):
  File "/home/site/wwwroot/.python_packages/lib/site-packages/botbuilder/core/bot_adapter.py", line 174, in run_pipeline
    return await self._middleware.receive_activity_with_status(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/site/wwwroot/.python_packages/lib/site-packages/botbuilder/core/middleware_set.py", line 69, in receive_activity_with_status
    return await self.receive_activity_internal(context, callback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/site/wwwroot/.python_packages/lib/site-packages/botbuilder/core/middleware_set.py", line 79, in receive_activity_internal
    return await callback(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/site/wwwroot/bots/dialog_bot.py", line 46, in on_turn
    await super().on_turn(turn_context)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/botbuilder/core/activity_handler.py", line 70, in on_turn
    await self.on_message_activity(turn_context)
  File "/home/site/wwwroot/bots/dialog_bot.py", line 80, in on_message_activity
    update_result = await turn_context.update_activity(new_activity)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/site/wwwroot/.python_packages/lib/site-packages/botbuilder/core/turn_context.py", line 235, in update_activity
    return await self._emit(
           ^^^^^^^^^^^^^^^^^
  File "/home/site/wwwroot/.python_packages/lib/site-packages/botbuilder/core/turn_context.py", line 303, in _emit
    return await logic
           ^^^^^^^^^^^
  File "/home/site/wwwroot/.python_packages/lib/site-packages/botbuilder/core/cloud_adapter_base.py", line 122, in update_activity
    response = await connector_client.conversations.update_activity(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/site/wwwroot/.python_packages/lib/site-packages/botframework/connector/aio/operations_async/_conversations_operations_async.py", line 434, in update_activity
    raise models.ErrorResponseException(self._deserialize, response)
botbuilder.schema._models_py3.ErrorResponseException: (ServiceError) Unknown
2024-07-10T09:21:43Z   [Error]   Error processing request: 'Internal.ConversationState'
Traceback (most recent call last):
  File "/home/site/wwwroot/.python_packages/lib/site-packages/botbuilder/core/bot_adapter.py", line 174, in run_pipeline
    return await self._middleware.receive_activity_with_status(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/site/wwwroot/.python_packages/lib/site-packages/botbuilder/core/middleware_set.py", line 69, in receive_activity_with_status
    return await self.receive_activity_internal(context, callback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/site/wwwroot/.python_packages/lib/site-packages/botbuilder/core/middleware_set.py", line 79, in receive_activity_internal
    return await callback(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/site/wwwroot/bots/dialog_bot.py", line 46, in on_turn
    await super().on_turn(turn_context)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/botbuilder/core/activity_handler.py", line 70, in on_turn
    await self.on_message_activity(turn_context)
  File "/home/site/wwwroot/bots/dialog_bot.py", line 80, in on_message_activity
    update_result = await turn_context.update_activity(new_activity)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/site/wwwroot/.python_packages/lib/site-packages/botbuilder/core/turn_context.py", line 235, in update_activity
    return await self._emit(
           ^^^^^^^^^^^^^^^^^
  File "/home/site/wwwroot/.python_packages/lib/site-packages/botbuilder/core/turn_context.py", line 303, in _emit
    return await logic
           ^^^^^^^^^^^
  File "/home/site/wwwroot/.python_packages/lib/site-packages/botbuilder/core/cloud_adapter_base.py", line 122, in update_activity
    response = await connector_client.conversations.update_activity(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/site/wwwroot/.python_packages/lib/site-packages/botframework/connector/aio/operations_async/_conversations_operations_async.py", line 434, in update_activity
    raise models.ErrorResponseException(self._deserialize, response)
botbuilder.schema._models_py3.ErrorResponseException: (ServiceError) Unknown

## Screenshots
Current code:
![image](https://github.com/microsoft/botbuilder-python/assets/119569146/a7185fc2-7992-4186-91b5-1c4af78976b3)
Code is not the same as the sample given by Microsoft as there is a reference to a variable "activity_id" which was not mentioned elsewhere hence I tried to use the previously initialised "activityId" instead

## Additional context
Currently using it as a Teams bot

**Comment by tracyboehrer** [comment]
What version of the SDK are you using?

**Comment by sethteo** [comment]
> What version of the SDK are you using?

@tracyboehrer thank you for the reply, I am currently using v4.15.0 running on python 3.11

**Comment by tracyboehrer** [comment]
Can you try 4.15.1+.  The latest should be fine too.  There was a fix related to update activity in CloudAdapter in that release.

**Comment by sethteo** [comment]
@tracyboehrer that seems to have fixed it thanks alot!
