### ISSUE TITLE
Adaptive Cards for Web Chat

### ISSUE THREAD

**Issue by vijaysaimutyala** [Microsoft/botbuilder-python#82]
I've tried implementing Adaptive Cards based on [this](https://docs.microsoft.com/en-us/adaptive-cards/get-started/bots). I could see that Activity supports **attachments** parameter and accepts inputs as shown in the above link to implement Adaptive Cards. I could not understand the contentUrl though. I've filled in the remaining fields and tried this. i'm encountering the below issue.

### My Activity
```
Activity(
        type=ActivityTypes.message,
        channel_id=request_activity.channel_id,
        conversation=request_activity.conversation,
        recipient=request_activity.from_property,
        from_property=request_activity.recipient,
        text=text,
        service_url=request_activity.service_url,
        attachments=Attachment(
            content_type="application/vnd.microsoft.card.adaptive",
            content={
                "type": "AdaptiveCard",
                "version": "1.0",
                "body": [
                    {
                    "type": "TextBlock",
                    "text": "Hello World!",
                    "size": "large"},
                    {
                    "type": "TextBlock",
                    "text": "*Sincerely yours,*"},
                    {
                    "type": "TextBlock",
                    "text": "Adaptive Cards",
                    "separation": "none"}],
                    "actions": [
                    {
                        "type": "Action.OpenUrl",
                        "url": "http://adaptivecards.io",
                        "title": "Learn More"
                    }
                    ]}),)
```
### Error Log
> ERROR:root:Error is: 
> Traceback (most recent call last):
>   File "D:\home\site\wwwroot\main.py", line 150, in messages
>     app.connector.conversations.send_to_conversation(activity['conversation']['id'], response_activity)
>   File "D:\home\python364x64\lib\site-packages\botframework\connector\operations\conversations_operations.py", line 224, in send_to_conversation
>     body_content = self._serialize.body(activity, 'Activity')
>   File "D:\home\python364x64\lib\site-packages\msrest\serialization.py", line 473, in body
>     errors = _recursive_validate(data_type, data_type, data)
>   File "D:\home\python364x64\lib\site-packages\msrest\serialization.py", line 124, in _recursive_validate
>     return data.validate()
>   File "D:\home\python364x64\lib\site-packages\msrest\serialization.py", line 184, in validate
>     validation_result += _recursive_validate(attr_name, attr_type, value)
>   File "D:\home\python364x64\lib\site-packages\msrest\serialization.py", line 116, in _recursive_validate
>     for content in data:
> TypeError: 'Attachment' object is not iterable

My target is to have a card with a button. I've already implemented the SuggestedActions with buttons, but I need the button to be always available just in case the user wants to visit the link again. Is there any issue with the way I implemented this? Any samples towards this will be helpful.

**Comment by vijaysaimutyala** [comment]
I should've googled better. @stevengum97 has already provided some guidance [here](https://stackoverflow.com/questions/50453157/adding-an-adaptive-card-to-bot-framework-with-python)
