### ISSUE TITLE
async support and documentation

### ISSUE THREAD

**Issue by Zerlok** [Microsoft/botbuilder-python#87]
Hello, I'm trying to use the bot connector for python project using the example [here](https://github.com/Microsoft/botbuilder-python/blob/master/samples/Echo-Connector-Bot/main.py) and it works fine.

My project uses aiohttp framework, so I'm trying to use async methods in bot builder lib, but I can't make it work. I've tried just simply add "_async" to the methods and await them - this does not work. Then use the **BotFrameworkAdapter** and its methods. Both choices throws **AttributeError** exception, that the client object has no attribute "_session".

```python
Traceback (most recent call last):
  File "/home/user/dev/myproject/.venv/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 378, in start
    resp = await self._request_handler(request)
  File "/home/user/dev/myproject/.venv/lib/python3.6/site-packages/aiohttp/web_app.py", line 341, in _handle
    resp = await handler(request)
  File "/home/user/dev/myproject/.venv/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 740, in _iter
    resp = await method()
  File "/home/user/dev/myproject/simple-check/main_async.py", line 73, in post
    await self.__handle_conversation_update_activity(activity)
  File "/home/user/dev/myproject/simple-check/main_async.py", line 43, in __handle_conversation_update_activity
    await connector.conversations.send_to_conversation_async(reply.conversation.id, reply)
  File "/home/user/dev/myproject/.venv/lib/python3.6/site-packages/botframework/connector/operations/conversations_operations_async.py", line 214, in send_to_conversation_async
    request, header_parameters, body_content, stream=False, **operation_config)
  File "/home/user/dev/myproject/.venv/lib/python3.6/site-packages/botframework/connector/async_mixin/async_mixin.py", line 69, in async_send
    session = self.creds.signed_session(self._session)
AttributeError: 'ServiceClient' object has no attribute '_session'
```

In my opinion, the **AsyncServiceClientMixin** class adds support for await/async, but the connector needs to be initialized with async client with session to work. I can't find any documentation in the lib with information how to do that correctly.

Here is a code of aiohttp server (methods copied from Echo-Connector-Bot sample and server is replaced with aiohttp application):

```python
from aiohttp.web import run_app
from aiohttp.web_app import Application
from aiohttp.web_response import json_response
from aiohttp.web_routedef import RouteTableDef
from aiohttp.web_urldispatcher import View
from botbuilder.schema import (Activity, ActivityTypes)
from botframework.connector import ConnectorClient
from botframework.connector.auth import (MicrosoftAppCredentials,
                                         JwtTokenValidation, SimpleCredentialProvider)

from os import getenv


APP_ID = getenv('MICROSOFT_BOT_BUILDER_APP_ID')
APP_PASSWORD = getenv('MICROSOFT_BOT_BUILDER_APP_PASSWORD')


routes = RouteTableDef()


@routes.view('/')
class BotView(View):
    def __create_reply_activity(self, request_activity, text):
        return Activity(
            type=ActivityTypes.message,
            channel_id=request_activity.channel_id,
            conversation=request_activity.conversation,
            recipient=request_activity.from_property,
            from_property=request_activity.recipient,
            text=text,
            service_url=request_activity.service_url)

    async def __handle_conversation_update_activity(self, activity):
        if activity.members_added[0].id != activity.recipient.id:
            credentials = MicrosoftAppCredentials(APP_ID, APP_PASSWORD)
            reply = self.__create_reply_activity(activity, 'Hello and welcome to the echo bot!')
            connector = ConnectorClient(credentials, base_url=reply.service_url)
            connector.conversations.send_to_conversation(reply.conversation.id, reply)
            # Throws exception:
            # await connector.conversations.send_to_conversation_async(reply.conversation.id, reply)

    async def __handle_message_activity(self, activity):
        credentials = MicrosoftAppCredentials(APP_ID, APP_PASSWORD)
        connector = ConnectorClient(credentials, base_url=activity.service_url)
        reply = self.__create_reply_activity(activity, 'You said: "%s"' % activity.text)
        connector.conversations.send_to_conversation(reply.conversation.id, reply)
        # Throws exception:
        # await connector.conversations.send_to_conversation_async(reply.conversation.id, reply)

    async def __handle_authentication(self, activity):
        credential_provider = SimpleCredentialProvider(APP_ID, APP_PASSWORD)
        try:
            auth = self.request.headers.get("Authorization")
            await JwtTokenValidation.assert_valid_activity(activity, auth, credential_provider)
            return True
        except Exception as err:
            return False

    async def post(self):
        data = await self.request.json()
        activity = Activity.deserialize(data)

        is_authorized = await self.__handle_authentication(activity)
        if not is_authorized:
            return json_response(
                data={'status': 'not authorized'},
                status=400,
            )

        if activity.type == ActivityTypes.conversation_update.value:
            await self.__handle_conversation_update_activity(activity)
        elif activity.type == ActivityTypes.message.value:
            await self.__handle_message_activity(activity)

        return json_response(
            data={'status': 'ok'},
            status=200,
        )


if __name__ == '__main__':
    app = Application()
    app.add_routes(routes)
    run_app(app, host='0.0.0.0', port=8000)
```

requirements:
```
aiohttp==3.3.2
botbuilder-core==4.0.0a4
botbuilder-schema==4.0.0a3
```

**Comment by stevengum** [comment]
@Zerlok to use the BotFrameworkAdapter and the async operations on the ConnectorClient, you'll need to use a specific commit from the msrest-for-python repo:

```
git+https://github.com/Azure/msrest-for-python.git@a997e97cd926c1eedfe4e5a3a52a637313fbd4e4
```

You can install this via the [requirements.txt](https://github.com/Microsoft/botbuilder-python/blob/master/libraries/botbuilder-core/requirements.txt#L1) which can be found in the botbuilder-core. This specific requirement can also be found in [botframework-connector](https://github.com/Microsoft/botbuilder-python/blob/master/libraries/botframework-connector/requirements.txt#L1). Can you try installing that and letting us know if it works?

**Comment by stevengum** [comment]
@Zerlok, once the async branch of `msrest` gets merged into master, using the `setup.py` dependencies will suffice. Until then, devs will need to `pip install -r requirements.txt` to get access to the async goodness (and use the SDK 😢). 

Any of the requirements.txt from the libraries in the repo will work, along with the samples' requirement.txt except for the "Echo-Connector-Bot" all have this dependency.

**Comment by stevengum** [comment]
Closing this issue, if you run into another similar issue please open a new one and provide the same level of detail.

**Comment by heitorrapela** [comment]
I'm having this problem and I can't fix it with pip install -e git+https://github.com/Azure/msrest-for-python.git@a997e97cd926c1eedfe4e5a3a52a637313fbd4e4#egg=msrest (The command is not work: Command "git reset --hard -q a997e97cd926c1eedfe4e5a3a52a637313fbd4e4" failed with error code 128 in ./botbuilder-python/samples/Rich-Cards-Bot/src/msrest
)
